//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.Client.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Level2.PlateLeveler.Client.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act 1m Ruler Cross.
        /// </summary>
        public static string Act1MRulerCross {
            get {
                return ResourceManager.GetString("Act1MRulerCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act 1m Ruler Length.
        /// </summary>
        public static string Act1MRulerLength {
            get {
                return ResourceManager.GetString("Act1MRulerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act 2m Ruler Length.
        /// </summary>
        public static string Act2MRulerLength {
            get {
                return ResourceManager.GetString("Act2MRulerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 1.
        /// </summary>
        public static string ActCurrentDrive1 {
            get {
                return ResourceManager.GetString("ActCurrentDrive1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 10.
        /// </summary>
        public static string ActCurrentDrive10 {
            get {
                return ResourceManager.GetString("ActCurrentDrive10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 11.
        /// </summary>
        public static string ActCurrentDrive11 {
            get {
                return ResourceManager.GetString("ActCurrentDrive11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 12.
        /// </summary>
        public static string ActCurrentDrive12 {
            get {
                return ResourceManager.GetString("ActCurrentDrive12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 13.
        /// </summary>
        public static string ActCurrentDrive13 {
            get {
                return ResourceManager.GetString("ActCurrentDrive13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 2.
        /// </summary>
        public static string ActCurrentDrive2 {
            get {
                return ResourceManager.GetString("ActCurrentDrive2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 3.
        /// </summary>
        public static string ActCurrentDrive3 {
            get {
                return ResourceManager.GetString("ActCurrentDrive3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 4.
        /// </summary>
        public static string ActCurrentDrive4 {
            get {
                return ResourceManager.GetString("ActCurrentDrive4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 5.
        /// </summary>
        public static string ActCurrentDrive5 {
            get {
                return ResourceManager.GetString("ActCurrentDrive5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 6.
        /// </summary>
        public static string ActCurrentDrive6 {
            get {
                return ResourceManager.GetString("ActCurrentDrive6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 7.
        /// </summary>
        public static string ActCurrentDrive7 {
            get {
                return ResourceManager.GetString("ActCurrentDrive7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 8.
        /// </summary>
        public static string ActCurrentDrive8 {
            get {
                return ResourceManager.GetString("ActCurrentDrive8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current Drive 9.
        /// </summary>
        public static string ActCurrentDrive9 {
            get {
                return ResourceManager.GetString("ActCurrentDrive9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act Curve Profile.
        /// </summary>
        public static string ActCurveProfile {
            get {
                return ResourceManager.GetString("ActCurveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Headposition.
        /// </summary>
        public static string ActHeadPos {
            get {
                return ResourceManager.GetString("ActHeadPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act  Leveler Inlet.
        /// </summary>
        public static string ActLevelerInlet {
            get {
                return ResourceManager.GetString("ActLevelerInlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act Leveler Outlet.
        /// </summary>
        public static string ActLevelerOutlet {
            get {
                return ResourceManager.GetString("ActLevelerOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act Middle Height.
        /// </summary>
        public static string ActMiddleHeight {
            get {
                return ResourceManager.GetString("ActMiddleHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Power Drive.
        /// </summary>
        public static string ActPowerDrive {
            get {
                return ResourceManager.GetString("ActPowerDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Speed.
        /// </summary>
        public static string ActSpeed {
            get {
                return ResourceManager.GetString("ActSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act Tilting Left.
        /// </summary>
        public static string ActTiltLeft {
            get {
                return ResourceManager.GetString("ActTiltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act Tilting Right.
        /// </summary>
        public static string ActTiltRight {
            get {
                return ResourceManager.GetString("ActTiltRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 1.
        /// </summary>
        public static string ActTorqueDrive1 {
            get {
                return ResourceManager.GetString("ActTorqueDrive1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 10.
        /// </summary>
        public static string ActTorqueDrive10 {
            get {
                return ResourceManager.GetString("ActTorqueDrive10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 11.
        /// </summary>
        public static string ActTorqueDrive11 {
            get {
                return ResourceManager.GetString("ActTorqueDrive11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 12.
        /// </summary>
        public static string ActTorqueDrive12 {
            get {
                return ResourceManager.GetString("ActTorqueDrive12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 13.
        /// </summary>
        public static string ActTorqueDrive13 {
            get {
                return ResourceManager.GetString("ActTorqueDrive13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 2.
        /// </summary>
        public static string ActTorqueDrive2 {
            get {
                return ResourceManager.GetString("ActTorqueDrive2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 3.
        /// </summary>
        public static string ActTorqueDrive3 {
            get {
                return ResourceManager.GetString("ActTorqueDrive3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 4.
        /// </summary>
        public static string ActTorqueDrive4 {
            get {
                return ResourceManager.GetString("ActTorqueDrive4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 5.
        /// </summary>
        public static string ActTorqueDrive5 {
            get {
                return ResourceManager.GetString("ActTorqueDrive5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 6.
        /// </summary>
        public static string ActTorqueDrive6 {
            get {
                return ResourceManager.GetString("ActTorqueDrive6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 7.
        /// </summary>
        public static string ActTorqueDrive7 {
            get {
                return ResourceManager.GetString("ActTorqueDrive7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 8.
        /// </summary>
        public static string ActTorqueDrive8 {
            get {
                return ResourceManager.GetString("ActTorqueDrive8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Torque Drive 9.
        /// </summary>
        public static string ActTorqueDrive9 {
            get {
                return ResourceManager.GetString("ActTorqueDrive9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string btnCopy {
            get {
                return ResourceManager.GetString("btnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Report.
        /// </summary>
        public static string btnPlateReport {
            get {
                return ResourceManager.GetString("btnPlateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Report.
        /// </summary>
        public static string btnReport {
            get {
                return ResourceManager.GetString("btnReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassette.
        /// </summary>
        public static string Cassette {
            get {
                return ResourceManager.GetString("Cassette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centering #1.
        /// </summary>
        public static string Centering1 {
            get {
                return ResourceManager.GetString("Centering1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centering #2.
        /// </summary>
        public static string Centering2 {
            get {
                return ResourceManager.GetString("Centering2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault Compensation.
        /// </summary>
        public static string FaultCompensation {
            get {
                return ResourceManager.GetString("FaultCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine  data.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Item0 {
            get {
                return ResourceManager.GetString("Item0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Off.
        /// </summary>
        public static string Item1 {
            get {
                return ResourceManager.GetString("Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Mode.
        /// </summary>
        public static string Item2 {
            get {
                return ResourceManager.GetString("Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Mode.
        /// </summary>
        public static string Item3 {
            get {
                return ResourceManager.GetString("Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Production.
        /// </summary>
        public static string Item4 {
            get {
                return ResourceManager.GetString("Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversing.
        /// </summary>
        public static string Item5 {
            get {
                return ResourceManager.GetString("Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault 1.
        /// </summary>
        public static string Item6 {
            get {
                return ResourceManager.GetString("Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault 2.
        /// </summary>
        public static string Item7 {
            get {
                return ResourceManager.GetString("Item7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault 3.
        /// </summary>
        public static string Item8 {
            get {
                return ResourceManager.GetString("Item8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Cassette.
        /// </summary>
        public static string lblActiveCassette {
            get {
                return ResourceManager.GetString("lblActiveCassette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing Diameter.
        /// </summary>
        public static string lblBearingDiameter {
            get {
                return ResourceManager.GetString("lblBearingDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassette No.
        /// </summary>
        public static string lblCassetteNo {
            get {
                return ResourceManager.GetString("lblCassetteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Height Bending.
        /// </summary>
        public static string lblCenterHeightBending {
            get {
                return ResourceManager.GetString("lblCenterHeightBending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastification Correction.
        /// </summary>
        public static string lblCorrPlastification {
            get {
                return ResourceManager.GetString("lblCorrPlastification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve Profile.
        /// </summary>
        public static string lblCurveProfile {
            get {
                return ResourceManager.GetString("lblCurveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance A.
        /// </summary>
        public static string lblDistanceA {
            get {
                return ResourceManager.GetString("lblDistanceA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance B.
        /// </summary>
        public static string lblDistanceB {
            get {
                return ResourceManager.GetString("lblDistanceB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance C.
        /// </summary>
        public static string lblDistanceC {
            get {
                return ResourceManager.GetString("lblDistanceC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EModule.
        /// </summary>
        public static string lblEModule {
            get {
                return ResourceManager.GetString("lblEModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Range Actual Yield Point.
        /// </summary>
        public static string lblEndRangeActYieldPoint {
            get {
                return ResourceManager.GetString("lblEndRangeActYieldPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Range Thickness.
        /// </summary>
        public static string lblEndRangeThickness {
            get {
                return ResourceManager.GetString("lblEndRangeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Range Width.
        /// </summary>
        public static string lblEndRangeWidth {
            get {
                return ResourceManager.GetString("lblEndRangeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Center Wave.
        /// </summary>
        public static string lblEvaluationCenterWave {
            get {
                return ResourceManager.GetString("lblEvaluationCenterWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Edge Wave.
        /// </summary>
        public static string lblEvaluationEdgeWave {
            get {
                return ResourceManager.GetString("lblEvaluationEdgeWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Ski.
        /// </summary>
        public static string lblEvaluationSki {
            get {
                return ResourceManager.GetString("lblEvaluationSki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Tilting.
        /// </summary>
        public static string lblEvaluationTilting {
            get {
                return ResourceManager.GetString("lblEvaluationTilting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap Cross Bow.
        /// </summary>
        public static string lblGapCrossBow {
            get {
                return ResourceManager.GetString("lblGapCrossBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap Length Bow.
        /// </summary>
        public static string lblGapLengthBow {
            get {
                return ResourceManager.GetString("lblGapLengthBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string lblLength {
            get {
                return ResourceManager.GetString("lblLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveling.
        /// </summary>
        public static string lblLeveling {
            get {
                return ResourceManager.GetString("lblLeveling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblLimitation {
            get {
                return ResourceManager.GetString("lblLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaterialID.
        /// </summary>
        public static string lblMaterialID {
            get {
                return ResourceManager.GetString("lblMaterialID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Adjustment.
        /// </summary>
        public static string lblMaxAdjustment {
            get {
                return ResourceManager.GetString("lblMaxAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Center Height Bending.
        /// </summary>
        public static string lblMaxCenterHeightBending {
            get {
                return ResourceManager.GetString("lblMaxCenterHeightBending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Cross Tilt Left.
        /// </summary>
        public static string lblMaxCrossTiltLeft {
            get {
                return ResourceManager.GetString("lblMaxCrossTiltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Cross Tilt Right.
        /// </summary>
        public static string lblMaxCrossTiltRight {
            get {
                return ResourceManager.GetString("lblMaxCrossTiltRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Height Center Wave.
        /// </summary>
        public static string lblMaxHeightCenterWave {
            get {
                return ResourceManager.GetString("lblMaxHeightCenterWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Height Edge Wave.
        /// </summary>
        public static string lblMaxHeightEdgeWave {
            get {
                return ResourceManager.GetString("lblMaxHeightEdgeWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Leveling Pressure.
        /// </summary>
        public static string lblMaxLevelingPressure {
            get {
                return ResourceManager.GetString("lblMaxLevelingPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Motor Power .
        /// </summary>
        public static string lblMaxMotorPower {
            get {
                return ResourceManager.GetString("lblMaxMotorPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Motor Torque.
        /// </summary>
        public static string lblMaxMotorTorque {
            get {
                return ResourceManager.GetString("lblMaxMotorTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Ski.
        /// </summary>
        public static string lblMaxSki {
            get {
                return ResourceManager.GetString("lblMaxSki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Thickness Plate.
        /// </summary>
        public static string lblMaxThicknessPlate {
            get {
                return ResourceManager.GetString("lblMaxThicknessPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Tilting.
        /// </summary>
        public static string lblMaxTilting {
            get {
                return ResourceManager.GetString("lblMaxTilting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Center Height Bending.
        /// </summary>
        public static string lblMinCenterHeightBending {
            get {
                return ResourceManager.GetString("lblMinCenterHeightBending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Cross Tilt Left.
        /// </summary>
        public static string lblMinCrossTiltLeft {
            get {
                return ResourceManager.GetString("lblMinCrossTiltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Cross Tilt Right.
        /// </summary>
        public static string lblMinCrossTiltRight {
            get {
                return ResourceManager.GetString("lblMinCrossTiltRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Height Center Wave.
        /// </summary>
        public static string lblMinHeightCenterWave {
            get {
                return ResourceManager.GetString("lblMinHeightCenterWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Height Edge Wave.
        /// </summary>
        public static string lblMinHeightEdgeWave {
            get {
                return ResourceManager.GetString("lblMinHeightEdgeWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Thickness Plate.
        /// </summary>
        public static string lblMinThicknessPlate {
            get {
                return ResourceManager.GetString("lblMinThicknessPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Rolls.
        /// </summary>
        public static string lblNoOfRolls {
            get {
                return ResourceManager.GetString("lblNoOfRolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet Compensation.
        /// </summary>
        public static string lblOffset {
            get {
                return ResourceManager.GetString("lblOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch Of Rolls.
        /// </summary>
        public static string lblPitchOfRolls {
            get {
                return ResourceManager.GetString("lblPitchOfRolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlateID.
        /// </summary>
        public static string lblPlateID {
            get {
                return ResourceManager.GetString("lblPlateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Length.
        /// </summary>
        public static string lblPlateLength {
            get {
                return ResourceManager.GetString("lblPlateLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Thickness.
        /// </summary>
        public static string lblPlateThickness {
            get {
                return ResourceManager.GetString("lblPlateThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Width.
        /// </summary>
        public static string lblPlateWidth {
            get {
                return ResourceManager.GetString("lblPlateWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Reports.
        /// </summary>
        public static string lblReport {
            get {
                return ResourceManager.GetString("lblReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Diameter.
        /// </summary>
        public static string lblRollDiameter {
            get {
                return ResourceManager.GetString("lblRollDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1M Ruler Cross.
        /// </summary>
        public static string lblRuler1MCross {
            get {
                return ResourceManager.GetString("lblRuler1MCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1M Ruler Length.
        /// </summary>
        public static string lblRuler1MLength {
            get {
                return ResourceManager.GetString("lblRuler1MLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2M Ruler Length.
        /// </summary>
        public static string lblRuler2MLength {
            get {
                return ResourceManager.GetString("lblRuler2MLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Range Actual Yield Point.
        /// </summary>
        public static string lblStartRangeActYieldPoint {
            get {
                return ResourceManager.GetString("lblStartRangeActYieldPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Range Thickness.
        /// </summary>
        public static string lblStartRangeThickness {
            get {
                return ResourceManager.GetString("lblStartRangeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Range Width.
        /// </summary>
        public static string lblStartRangeWidth {
            get {
                return ResourceManager.GetString("lblStartRangeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steelgrade.
        /// </summary>
        public static string lblSteelgrade {
            get {
                return ResourceManager.GetString("lblSteelgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tensile Strength.
        /// </summary>
        public static string lblTensileStrength {
            get {
                return ResourceManager.GetString("lblTensileStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string lblThickness {
            get {
                return ResourceManager.GetString("lblThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilting Left.
        /// </summary>
        public static string lblTiltLeft {
            get {
                return ResourceManager.GetString("lblTiltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilting Right.
        /// </summary>
        public static string lblTiltRight {
            get {
                return ResourceManager.GetString("lblTiltRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string lblValue {
            get {
                return ResourceManager.GetString("lblValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string lblWidth {
            get {
                return ResourceManager.GetString("lblWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield Point.
        /// </summary>
        public static string lblYieldPoint {
            get {
                return ResourceManager.GetString("lblYieldPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveler.
        /// </summary>
        public static string Leveler {
            get {
                return ResourceManager.GetString("Leveler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitation.
        /// </summary>
        public static string Limitation {
            get {
                return ResourceManager.GetString("Limitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line State.
        /// </summary>
        public static string LineState {
            get {
                return ResourceManager.GetString("LineState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationState {
            get {
                return ResourceManager.GetString("LocationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material ID.
        /// </summary>
        public static string MaterialID {
            get {
                return ResourceManager.GetString("MaterialID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring.
        /// </summary>
        public static string Measuring {
            get {
                return ResourceManager.GetString("Measuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Code.
        /// </summary>
        public static string MeasuringCode {
            get {
                return ResourceManager.GetString("MeasuringCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Leveling.
        /// </summary>
        public static string NoOfLeveling {
            get {
                return ResourceManager.GetString("NoOfLeveling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDI Data.
        /// </summary>
        public static string PDI {
            get {
                return ResourceManager.GetString("PDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastification.
        /// </summary>
        public static string Plastification {
            get {
                return ResourceManager.GetString("Plastification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Tracking.
        /// </summary>
        public static string PlateTracking {
            get {
                return ResourceManager.GetString("PlateTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Pos {
            get {
                return ResourceManager.GetString("Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presettings.
        /// </summary>
        public static string Presettings {
            get {
                return ResourceManager.GetString("Presettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet Presettings.
        /// </summary>
        public static string PresettingsOutlet {
            get {
                return ResourceManager.GetString("PresettingsOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorities.
        /// </summary>
        public static string Priorities {
            get {
                return ResourceManager.GetString("Priorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority ID.
        /// </summary>
        public static string PriorityID {
            get {
                return ResourceManager.GetString("PriorityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Report.
        /// </summary>
        public static string ProductionReport {
            get {
                return ResourceManager.GetString("ProductionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string rbExport {
            get {
                return ResourceManager.GetString("rbExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string rbPreview {
            get {
                return ResourceManager.GetString("rbPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string rbPrint {
            get {
                return ResourceManager.GetString("rbPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 1m Ruler Cross.
        /// </summary>
        public static string Set1MRulerCross {
            get {
                return ResourceManager.GetString("Set1MRulerCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 1m Ruler Length.
        /// </summary>
        public static string Set1MRulerLength {
            get {
                return ResourceManager.GetString("Set1MRulerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 2m Ruler Length.
        /// </summary>
        public static string Set2MRulerLength {
            get {
                return ResourceManager.GetString("Set2MRulerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Curve Profile.
        /// </summary>
        public static string SetCurveProfile {
            get {
                return ResourceManager.GetString("SetCurveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Inlet.
        /// </summary>
        public static string SetLevelerInlet {
            get {
                return ResourceManager.GetString("SetLevelerInlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Outlet.
        /// </summary>
        public static string SetLevelerOutlet {
            get {
                return ResourceManager.GetString("SetLevelerOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Middle Height.
        /// </summary>
        public static string SetMiddleHeight {
            get {
                return ResourceManager.GetString("SetMiddleHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Tilt Left.
        /// </summary>
        public static string SetTiltLeft {
            get {
                return ResourceManager.GetString("SetTiltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Tilt Right.
        /// </summary>
        public static string SetTiltRight {
            get {
                return ResourceManager.GetString("SetTiltRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
    }
}
