//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle �nderungen an dieser Datei f�hren m�glicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle �nderungen an dieser Datei werden �berschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
   using System;
   using System.Collections.Generic;
   using System.ComponentModel;

   public partial class ActualValue : INotifyPropertyChanged
   {
      private long _Pkey_ActVal;
      public long Pkey_ActVal
      {
         get { return _Pkey_ActVal; }
         set { PropertyChanged.ChangeAndNotify(ref _Pkey_ActVal, value, () => Pkey_ActVal); }
      }

      private string _PlateID;
      public string PlateID
      {
         get { return _PlateID; }
         set { PropertyChanged.ChangeAndNotify(ref _PlateID, value, () => PlateID); }
      }

      private string _MaterialID;
      public string MaterialID
      {
         get { return _MaterialID; }
         set { PropertyChanged.ChangeAndNotify(ref _MaterialID, value, () => MaterialID); }
      }
      private DateTime _Date;
      public DateTime Date
      {
         get { return _Date; }
         set { PropertyChanged.ChangeAndNotify(ref _Date, value, () => Date); }
      }

      private Nullable<int> _Pos;
      public Nullable<int> Pos
      {
         get { return _Pos; }
         set { PropertyChanged.ChangeAndNotify(ref _Pos, value, () => Pos); }
      }

      private Nullable<float> _ActHeadPos;
      public Nullable<float> ActHeadPos
      {
         get { return _ActHeadPos; }
         set { PropertyChanged.ChangeAndNotify(ref _ActHeadPos, value, () => ActHeadPos); }
      }

      private Nullable<float> _ActLevelerInlet;
      public Nullable<float> ActLevelerInlet
      {
         get { return _ActLevelerInlet; }
         set { PropertyChanged.ChangeAndNotify(ref _ActLevelerInlet, value, () => ActLevelerInlet); }
      }

      private Nullable<float> _ActLevelerOutlet;
      public Nullable<float> ActLevelerOutlet
      {
         get { return _ActLevelerOutlet; }
         set { PropertyChanged.ChangeAndNotify(ref _ActLevelerOutlet, value, () => ActLevelerOutlet); }
      }

      private Nullable<float> _ActTiltLeft;
      public Nullable<float> ActTiltLeft
      {
         get { return _ActTiltLeft; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTiltLeft, value, () => ActTiltLeft); }
      }

      private Nullable<float> _ActTiltRight;
      public Nullable<float> ActTiltRight
      {
         get { return _ActTiltRight; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTiltRight, value, () => ActTiltRight); }
      }

      private Nullable<float> _ActMiddleHeight;
      public Nullable<float> ActMiddleHeight
      {
         get { return _ActMiddleHeight; }
         set { PropertyChanged.ChangeAndNotify(ref _ActMiddleHeight, value, () => ActMiddleHeight); }
      }

      private Nullable<float> _ActCurveProfile;
      public Nullable<float> ActCurveProfile
      {
         get { return _ActCurveProfile; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurveProfile, value, () => ActCurveProfile); }
      }

      private Nullable<float> _ActPowerDrive1;
      public Nullable<float> ActPowerDrive1
      {
         get { return _ActPowerDrive1; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive1, value, () => ActPowerDrive1); }
      }

      private Nullable<float> _ActPowerDrive2;
      public Nullable<float> ActPowerDrive2
      {
         get { return _ActPowerDrive2; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive2, value, () => ActPowerDrive2); }
      }

      private Nullable<float> _ActPowerDrive3;
      public Nullable<float> ActPowerDrive3
      {
         get { return _ActPowerDrive3; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive3, value, () => ActPowerDrive3); }
      }

      private Nullable<float> _ActPowerDrive4;
      public Nullable<float> ActPowerDrive4
      {
         get { return _ActPowerDrive4; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive4, value, () => ActPowerDrive4); }
      }
      private Nullable<float> _ActPowerDrive5;
      public Nullable<float> ActPowerDrive5
      {
         get { return _ActPowerDrive5; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive5, value, () => ActPowerDrive5); }
      }
      private Nullable<float> _ActPowerDrive6;
      public Nullable<float> ActPowerDrive6
      {
         get { return _ActPowerDrive6; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive6, value, () => ActPowerDrive6); }
      }
      private Nullable<float> _ActPowerDrive7;
      public Nullable<float> ActPowerDrive7
      {
         get { return _ActPowerDrive7; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive7, value, () => ActPowerDrive7); }
      }
      private Nullable<float> _ActPowerDrive8;
      public Nullable<float> ActPowerDrive8
      {
         get { return _ActPowerDrive8; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive8, value, () => ActPowerDrive8); }
      }
      private Nullable<float> _ActPowerDrive9;
      public Nullable<float> ActPowerDrive9
      {
         get { return _ActPowerDrive9; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive9, value, () => ActPowerDrive9); }
      }
      private Nullable<float> _ActPowerDrive10;
      public Nullable<float> ActPowerDrive10
      {
         get { return _ActPowerDrive10; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive10, value, () => ActPowerDrive10); }
      }
      private Nullable<float> _ActPowerDrive11;
      public Nullable<float> ActPowerDrive11
      {
         get { return _ActPowerDrive11; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive11, value, () => ActPowerDrive11); }
      }
      private Nullable<float> _ActPowerDrive12;
      public Nullable<float> ActPowerDrive12
      {
         get { return _ActPowerDrive11; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive12, value, () => ActPowerDrive12); }
      }
      private Nullable<float> _ActPowerDrive13;
      public Nullable<float> ActPowerDrive13
      {
         get { return _ActPowerDrive13; }
         set { PropertyChanged.ChangeAndNotify(ref _ActPowerDrive13, value, () => ActPowerDrive13); }
      }
      private Nullable<float> _ActTorqueDrive1;
      public Nullable<float> ActTorqueDrive1
      {
         get { return _ActTorqueDrive1; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive1, value, () => ActTorqueDrive1); }
      }

      private Nullable<float> _ActTorqueDrive2;
      public Nullable<float> ActTorqueDrive2
      {
         get { return _ActTorqueDrive2; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive2, value, () => ActTorqueDrive2); }
      }

      private Nullable<float> _ActTorqueDrive3;
      public Nullable<float> ActTorqueDrive3
      {
         get { return _ActTorqueDrive3; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive3, value, () => ActTorqueDrive3); }
      }

      private Nullable<float> _ActTorqueDrive4;
      public Nullable<float> ActTorqueDrive4
      {
         get { return _ActTorqueDrive4; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive4, value, () => ActTorqueDrive4); }
      }
      private Nullable<float> _ActTorqueDrive5;
      public Nullable<float> ActTorqueDrive5
      {
         get { return _ActTorqueDrive5; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive5, value, () => ActTorqueDrive5); }
      }

      private Nullable<float> _ActTorqueDrive6;
      public Nullable<float> ActTorqueDrive6
      {
         get { return _ActTorqueDrive6; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive6, value, () => ActTorqueDrive6); }
      }

      private Nullable<float> _ActTorqueDrive7;
      public Nullable<float> ActTorqueDrive7
      {
         get { return _ActTorqueDrive7; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive7, value, () => ActTorqueDrive7); }
      }

      private Nullable<float> _ActTorqueDrive8;
      public Nullable<float> ActTorqueDrive8
      {
         get { return _ActTorqueDrive8; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive8, value, () => ActTorqueDrive8); }
      }

      private Nullable<float> _ActTorqueDrive9;
      public Nullable<float> ActTorqueDrive9
      {
         get { return _ActTorqueDrive9; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive9, value, () => ActTorqueDrive9); }
      }

      private Nullable<float> _ActTorqueDrive10;
      public Nullable<float> ActTorqueDrive10
      {
         get { return _ActTorqueDrive10; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive10, value, () => ActTorqueDrive10); }
      }

      private Nullable<float> _ActTorqueDrive11;
      public Nullable<float> ActTorqueDrive11
      {
         get { return _ActTorqueDrive11; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive11, value, () => ActTorqueDrive11); }
      }

      private Nullable<float> _ActTorqueDrive12;
      public Nullable<float> ActTorqueDrive12
      {
         get { return _ActTorqueDrive12; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive12, value, () => ActTorqueDrive12); }
      }

      private Nullable<float> _ActTorqueDrive13;
      public Nullable<float> ActTorqueDrive13
      {
         get { return _ActTorqueDrive13; }
         set { PropertyChanged.ChangeAndNotify(ref _ActTorqueDrive13, value, () => ActTorqueDrive13); }
      }

      private Nullable<float> _ActCurrentDrive1;
      public Nullable<float> ActCurrentDrive1
      {
         get { return _ActCurrentDrive1; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive1, value, () => ActCurrentDrive1); }
      }

      private Nullable<float> _ActCurrentDrive2;
      public Nullable<float> ActCurrentDrive2
      {
         get { return _ActCurrentDrive2; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive2, value, () => ActCurrentDrive2); }
      }

      private Nullable<float> _ActCurrentDrive3;
      public Nullable<float> ActCurrentDrive3
      {
         get { return _ActCurrentDrive3; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive3, value, () => ActCurrentDrive3); }
      }

      private Nullable<float> _ActCurrentDrive4;
      public Nullable<float> ActCurrentDrive4
      {
         get { return _ActCurrentDrive4; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive4, value, () => ActCurrentDrive4); }
      }
      private Nullable<float> _ActCurrentDrive5;
      public Nullable<float> ActCurrentDrive5
      {
         get { return _ActCurrentDrive5; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive5, value, () => ActCurrentDrive5); }
      }
      private Nullable<float> _ActCurrentDrive6;
      public Nullable<float> ActCurrentDrive6
      {
         get { return _ActCurrentDrive6; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive6, value, () => ActCurrentDrive6); }
      }
      private Nullable<float> _ActCurrentDrive7;
      public Nullable<float> ActCurrentDrive7
      {
         get { return _ActCurrentDrive7; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive7, value, () => ActCurrentDrive7); }
      }
      private Nullable<float> _ActCurrentDrive8;
      public Nullable<float> ActCurrentDrive8
      {
         get { return _ActCurrentDrive8; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive8, value, () => ActCurrentDrive8); }
      }
      private Nullable<float> _ActCurrentDrive9;
      public Nullable<float> ActCurrentDrive9
      {
         get { return _ActCurrentDrive9; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive9, value, () => ActCurrentDrive9); }
      }
      private Nullable<float> _ActCurrentDrive10;
      public Nullable<float> ActCurrentDrive10
      {
         get { return _ActCurrentDrive10; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive10, value, () => ActCurrentDrive10); }
      }
      private Nullable<float> _ActCurrentDrive11;
      public Nullable<float> ActCurrentDrive11
      {
         get { return _ActCurrentDrive11; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive11, value, () => ActCurrentDrive11); }
      }
      private Nullable<float> _ActCurrentDrive12;
      public Nullable<float> ActCurrentDrive12
      {
         get { return _ActCurrentDrive12; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive12, value, () => ActCurrentDrive12); }
      }

      private Nullable<float> _ActCurrentDrive13;
      public Nullable<float> ActCurrentDrive13
      {
         get { return _ActCurrentDrive13; }
         set { PropertyChanged.ChangeAndNotify(ref _ActCurrentDrive13, value, () => ActCurrentDrive13); }
      }


      private Nullable<float> _ActSpeed;
      public Nullable<float> ActSpeed
      {
         get { return _ActSpeed; }
         set { PropertyChanged.ChangeAndNotify(ref _ActSpeed, value, () => ActSpeed); }
      }


      public event PropertyChangedEventHandler PropertyChanged;

      public void SetActualValue(ActualMeasureData data, int pos)
      {
         PlateID = data.PlateID;
         Pos = pos;
         Date = DateTime.Now;
         ActCurveProfile = data.ActCurveProfile;
         ActHeadPos = data.ActHeadPos;
         ActLevelerInlet = data.ActLevelerInlet;
         ActLevelerOutlet = data.ActLevelerOutlet;
         ActMiddleHeight = data.ActMiddleHeight;
         ActSpeed = data.ActSpeed;
         ActTiltLeft = data.ActTiltingLeft;
         ActTiltRight = data.ActTiltingRight;

         ActCurrentDrive13 = data.ActCurrentDrive13;
         ActCurrentDrive12 = data.ActCurrentDrive12;
         ActCurrentDrive11 = data.ActCurrentDrive11;
         ActCurrentDrive10 = data.ActCurrentDrive10;
         ActCurrentDrive9 = data.ActCurrentDrive9;
         ActCurrentDrive8 = data.ActCurrentDrive8;
         ActCurrentDrive7 = data.ActCurrentDrive7;
         ActCurrentDrive6 = data.ActCurrentDrive6;
         ActCurrentDrive5 = data.ActCurrentDrive5;
         ActCurrentDrive4 = data.ActCurrentDrive4;
         ActCurrentDrive3 = data.ActCurrentDrive3;
         ActCurrentDrive2 = data.ActCurrentDrive2;
         ActCurrentDrive1 = data.ActCurrentDrive1;

         //if (data.ActCurrentDrive.Length > 3)
         //{
         //   ActCurrentDrive4 = data.ActCurrentDrive[3];
         //   if (data.ActCurrentDrive.Length > 2)
         //   {
         //      ActCurrentDrive3 = data.ActCurrentDrive[2];
         //      if (data.ActCurrentDrive.Length > 1)
         //      {
         //         ActCurrentDrive2 = data.ActCurrentDrive[1];
         //         if (data.ActCurrentDrive.Length > 0)
         //         {
         //            ActCurrentDrive1 = data.ActCurrentDrive[0];
         //         }
         //      }
         //   }
         //}

         ActPowerDrive13 = data.ActPowerDrive13;
         ActPowerDrive12 = data.ActPowerDrive12;
         ActPowerDrive11 = data.ActPowerDrive11;
         ActPowerDrive10 = data.ActPowerDrive10;
         ActPowerDrive9 = data.ActPowerDrive9;
         ActPowerDrive8 = data.ActPowerDrive8;
         ActPowerDrive7 = data.ActPowerDrive7;
         ActPowerDrive6 = data.ActPowerDrive6;
         ActPowerDrive5 = data.ActPowerDrive5;
         ActPowerDrive4 = data.ActPowerDrive4;
         ActPowerDrive3 = data.ActPowerDrive3;
         ActPowerDrive2 = data.ActPowerDrive2;
         ActPowerDrive1 = data.ActPowerDrive1;


         //if (data.ActPowerDrive.Length > 3)
         //{
         //   ActPowerDrive4 = data.ActPowerDrive[3];
         //   if (data.ActPowerDrive.Length > 2)
         //   {
         //      ActPowerDrive3 = data.ActPowerDrive[2];
         //      if (data.ActPowerDrive.Length > 1)
         //      {
         //         ActPowerDrive2 = data.ActPowerDrive[1];
         //         if (data.ActPowerDrive.Length > 0)
         //         {
         //            ActPowerDrive1 = data.ActPowerDrive[0];
         //         }
         //      }
         //   }
         //}
         ActTorqueDrive13 = data.ActTorqueDrive13;
         ActTorqueDrive12 = data.ActTorqueDrive12;
         ActTorqueDrive11 = data.ActTorqueDrive11;
         ActTorqueDrive10 = data.ActTorqueDrive10;
         ActTorqueDrive9 = data.ActTorqueDrive9;
         ActTorqueDrive8 = data.ActTorqueDrive8;
         ActTorqueDrive7 = data.ActTorqueDrive7;
         ActTorqueDrive6 = data.ActTorqueDrive6;
         ActTorqueDrive5 = data.ActTorqueDrive5;
         ActTorqueDrive4 = data.ActTorqueDrive4;
         ActTorqueDrive3 = data.ActTorqueDrive3;
         ActTorqueDrive2 = data.ActTorqueDrive2;
         ActTorqueDrive1 = data.ActTorqueDrive1;

         //if (data.ActTorqueDrive.Length > 3)
         //{
         //   ActTorqueDrive4 = data.ActTorqueDrive[3];
         //   if (data.ActPowerDrive.Length > 2)
         //   {
         //      ActTorqueDrive3 = data.ActTorqueDrive[2];
         //      if (data.ActTorqueDrive.Length > 1)
         //      {
         //         ActTorqueDrive2 = data.ActTorqueDrive[1];
         //         if (data.ActTorqueDrive.Length > 0)
         //         {
         //            ActTorqueDrive1 = data.ActTorqueDrive[0];
         //         }
         //      }
         //   }
         //}
      }
   }
}


