//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
    using System;
    using System.Collections.Generic;

    public partial class Cassette : ICassette {
        public int CassetteNo { get; set; }
        public Nullable<int> NoOfRolls { get; set; }
        public Nullable<float> BearingDiameter { get; set; }
        public Nullable<int> PitchOfRolls { get; set; }
        public Nullable<float> DistanceA { get; set; }
        public Nullable<float> DistanceB { get; set; }
        public Nullable<float> DistanceC { get; set; }
        public Nullable<float> MaxMotorPower { get; set; }
        public Nullable<float> MaxMotorTorque { get; set; }
        public Nullable<float> MinThicknessPlate { get; set; }
        public Nullable<float> MaxThicknessPlate { get; set; }
        public Nullable<float> MaxAdjustment { get; set; }
        public Nullable<float> MaxCenterHeightBending { get; set; }
        public Nullable<float> MinCenterHeightBending { get; set; }
        public Nullable<float> MaxCrossTiltLeft { get; set; }
        public Nullable<float> MinCrossTiltLeft { get; set; }
        public Nullable<float> MaxCrossTiltRight { get; set; }
        public Nullable<float> MinCrossTiltRight { get; set; }
        public Nullable<float> RollDiameter { get; set; }
        public Nullable<float> MaxLevelingPressure { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<float> MaxSelectThickness { get; set; }
    }
}
