//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle �nderungen an dieser Datei f�hren m�glicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle �nderungen an dieser Datei werden �berschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
   using System;
   using System.Collections.Generic;
   using System.ComponentModel;

    public partial class FaultCompensation : INotifyPropertyChanged, IFaultCompensation {
        private long _pKEY_FC;
        public long PKEY_FC {
            get { return _pKEY_FC; }
            set { PropertyChanged.ChangeAndNotify(ref _pKEY_FC, value, () => PKEY_FC); }
        }

        private Nullable<int> _edgeWave;
        [Priorities("EdgeWave")]
        public Nullable<int> EdgeWave {
            get { return _edgeWave; }
            set { PropertyChanged.ChangeAndNotify(ref _edgeWave, value, () => EdgeWave); }
        }

        private Nullable<int> _centerWave;
        [Priorities("CenterWave")]
        public Nullable<int> CenterWave {
            get { return _centerWave; }
            set { PropertyChanged.ChangeAndNotify(ref _centerWave, value, () => CenterWave); }
        }

        private Nullable<int> _ski;
        [Priorities("Ski")]
        public Nullable<int> Ski {
            get { return _ski; }
            set { PropertyChanged.ChangeAndNotify(ref _ski, value, () => Ski); }
        }

        private Nullable<int> _tilting;
        [Priorities("Tilting")]
        public Nullable<int> Tilting {
            get { return _tilting; }
            set { PropertyChanged.ChangeAndNotify(ref _tilting, value, () => Tilting); }
        }

        private Nullable<int> _cassetteNo;
        public Nullable<int> CassetteNo {
            get { return _cassetteNo; }
            set { PropertyChanged.ChangeAndNotify(ref _cassetteNo, value, () => CassetteNo); }
        }

        private Nullable<float> _maxHeightEdgeWave;
        public Nullable<float> MaxHeightEdgeWave {
            get { return _maxHeightEdgeWave; }
            set { PropertyChanged.ChangeAndNotify(ref _maxHeightEdgeWave, value, () => MaxHeightEdgeWave); }
        }

        private Nullable<float> _evaluationEdgeWave;
        public Nullable<float> EvaluationEdgeWave {
            get { return _evaluationEdgeWave; }
            set { PropertyChanged.ChangeAndNotify(ref _evaluationEdgeWave, value, () => EvaluationEdgeWave); }
        }

        private Nullable<float> _evaluationTilting;
        public Nullable<float> EvaluationTilting {
            get { return _evaluationTilting; }
            set { PropertyChanged.ChangeAndNotify(ref _evaluationTilting, value, () => EvaluationTilting); }
        }

        private Nullable<float> _maxHeightCenterWave;
        public Nullable<float> MaxHeightCenterWave {
            get { return _maxHeightCenterWave; }
            set { PropertyChanged.ChangeAndNotify(ref _maxHeightCenterWave, value, () => MaxHeightCenterWave); }
        }

        private Nullable<float> _evaluationCenterWave;
        public Nullable<float> EvaluationCenterWave {
            get { return _evaluationCenterWave; }
            set { PropertyChanged.ChangeAndNotify(ref _evaluationCenterWave, value, () => EvaluationCenterWave); }
        }

        private Nullable<float> _maxSki;
        public Nullable<float> MaxSki {
            get { return _maxSki; }
            set { PropertyChanged.ChangeAndNotify(ref _maxSki, value, () => MaxSki); }
        }

        private Nullable<float> _evaluationSki;
        public Nullable<float> EvaluationSki {
            get { return _evaluationSki; }
            set { PropertyChanged.ChangeAndNotify(ref _evaluationSki, value, () => EvaluationSki); }
        }

        private Nullable<float> _maxTilting;
        public Nullable<float> MaxTilting {
            get { return _maxTilting; }
            set { PropertyChanged.ChangeAndNotify(ref _maxTilting, value, () => MaxTilting); }
        }

        private IPriorityList _priorities;
        public IPriorityList Priorities {
            get { return _priorities; }
            set { _priorities = value; }
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }
}
