//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
    using System;
    using System.Collections.Generic;

    public partial class Flatness : IFlatness {
        public long Pkey_Flatness { get; set; }
        public string PlateID { get; set; }
        public string MaterialID { get; set; }
        public int PlateInTol { get; set; }
        public int MeasuringCode { get; set; }
        public int MeasuringRange { get; set; }
        public float MeanAmpWaveLeft { get; set; }
        public float MeanAmpWaveCenter { get; set; }
        public float MeanAmpRight { get; set; }
        public float SkiHead { get; set; }
        public float SkiTail { get; set; }
        public float HeightWaveLeft { get; set; }
        public float YPosWaveLeft { get; set; }
        public float LengthWaveLeft { get; set; }
        public int NumberWaveLeft { get; set; }
        public float HeightWaveQuarterLeft { get; set; }
        public float YPosWaveQuarterLeft { get; set; }
        public float LengthWaveQuarterLeft { get; set; }
        public int NumberWaveQuarterLeft { get; set; }
        public float HeightWaveCenter { get; set; }
        public float YPosWaveCenter { get; set; }
        public float LengthWaveCenter { get; set; }
        public int NumberWaveCenter { get; set; }
        public float HeightWaveQuarterRight { get; set; }
        public float YPosWaveQuarterRight { get; set; }
        public float LengthWaveQuarterRight { get; set; }
        public int NumberWaveQuarterRight { get; set; }
        public float HeightWaveRight { get; set; }
        public float YPosWaveRight { get; set; }
        public float LengthWaveRight { get; set; }
        public int NumberWaveRight { get; set; }
        public float GapLengthBow { get; set; }
        public float MaxGapLengthBow { get; set; }
        public float XPosLengthBow { get; set; }
        public float YPosLengthBow { get; set; }
        public float GapCrossBow { get; set; }
        public float MaxGapCrossBow { get; set; }
        public float XPosCrossBow { get; set; }
        public float YPosCrossBow { get; set; }
        public float Ruler1MCross { get; set; }
        public float ActRuler1MCross { get; set; }
        public float XPosRuler1MCross { get; set; }
        public float YPosRuler1MCross { get; set; }
        public float Ruler1MLength { get; set; }
        public float ActRuler1MLength { get; set; }
        public float XPosRuler1MLength { get; set; }
        public float YPosRuler1MLength { get; set; }
        public float Ruler2MLength { get; set; }
        public float ActRuler2MLength { get; set; }
        public float XPosRuler2MLength { get; set; }
        public float YPosRuler2MLength { get; set; }
        public float MaxPlateWidth { get; set; }
        public float MinPlateWidth { get; set; }
        public float MeanPlateWidth { get; set; }
        public float MaxDeviationOfCenterLine { get; set; }
    }
}
