//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
    using System;
    using System.Collections.Generic;
    
    public partial class L2_MODEL_L3_PLATE_REPORT
    {
        public long PKEY_PROD { get; set; }
        public Nullable<System.DateTime> ProdDateTime { get; set; }
        public string PlateID { get; set; }
        public string MaterialID { get; set; }
        public Nullable<int> Leveling { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> NoOfLeveling { get; set; }
        public Nullable<int> CassetteNo { get; set; }
        public Nullable<decimal> SetLevelerInlet { get; set; }
        public Nullable<decimal> SetLevelerOutlet { get; set; }
        public Nullable<decimal> SetTiltLeft { get; set; }
        public Nullable<decimal> SetTiltRight { get; set; }
        public Nullable<decimal> SetMiddleHeight { get; set; }
        public Nullable<decimal> SetCurveProfile { get; set; }
        public Nullable<decimal> ActLevelerInlet { get; set; }
        public Nullable<decimal> ActLevelerOutlet { get; set; }
        public Nullable<decimal> ActTiltLeft { get; set; }
        public Nullable<decimal> ActTiltRight { get; set; }
        public Nullable<decimal> ActMiddleHeight { get; set; }
        public Nullable<decimal> ActCurveProfile { get; set; }
        public Nullable<decimal> TensileStrength { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> ActTemperature { get; set; }
    }
}
