//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
    using System;
    using System.Collections.Generic;
    
    public partial class L3_L2_MODEL_PDI
    {
        public long PKEY_PDI { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string PlateID { get; set; }
        public string MaterialID { get; set; }
        public string SteelGrade { get; set; }
        public decimal PlateLength { get; set; }
        public decimal PlateWidth { get; set; }
        public decimal PlateThickness { get; set; }
        public decimal YieldPoint { get; set; }
        public decimal TensileStrength { get; set; }
        public decimal Ruler1MCross { get; set; }
        public decimal Ruler1MLength { get; set; }
        public decimal Ruler2MLength { get; set; }
        public decimal EModule { get; set; }
        public short Leveling { get; set; }
        public short Location { get; set; }
        public int State { get; set; }
        public string ErrorMessage { get; set; }
    }
}
