//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LEVELEREntities : DbContext
    {
        public LEVELEREntities()
            : base("name=LEVELEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActualValue> ActualValues { get; set; }
        public DbSet<Cassette> Cassettes { get; set; }
        public DbSet<FaultCompensation> FaultCompensations { get; set; }
        public DbSet<Flatness> Flatnesses { get; set; }
        public DbSet<Limitation> Limitations { get; set; }
        public DbSet<LineState> LineStates { get; set; }
        public DbSet<PDI> PDIs { get; set; }
        public DbSet<PreSetting> PreSettings { get; set; }
        public DbSet<PreSettingsOutlet> PreSettingsOutlets { get; set; }
        public DbSet<ProductionReport> ProductionReports { get; set; }
        public DbSet<Produkt> Produkts { get; set; }
        public DbSet<Temp> Temps { get; set; }
        public DbSet<AuxVariable> AuxVariables { get; set; }
        public DbSet<L3_L2_MODEL_PDI> L3_L2_MODEL_PDI { get; set; }
        public DbSet<L2_MODEL_L3_TRACKING> L2_MODEL_L3_TRACKING { get; set; }
        public DbSet<L2_MODEL_L3_PLATE_REPORT> L2_MODEL_L3_PLATE_REPORT { get; set; }
        public DbSet<Steelgrade> Steelgrades { get; set; }
    }
}
