//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle �nderungen an dieser Datei f�hren m�glicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle �nderungen an dieser Datei werden �berschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
   using System;
   using System.Collections.Generic;
   using System.ComponentModel;

   [AttributeUsage(AttributeTargets.Property, AllowMultiple = true)]
   public partial class Limitation : Attribute, INotifyPropertyChanged
   {
      public Limitation()
      {
      }
      public Limitation(string limit)
      {
         _limit = limit;
      }
      public Limitation(string limit, int pkey)
      {
         _limit = limit;
         _pkey_Limitation = pkey;
      }
      private int _pkey_Limitation;
      public int Pkey_Limitation
      {
         get { return _pkey_Limitation; }
         set { PropertyChanged.ChangeAndNotify(ref _pkey_Limitation, value, () => Pkey_Limitation); }
      }

      private string _limit;
      public string Limit
      {
         get { return _limit; }
         set { PropertyChanged.ChangeAndNotify(ref _limit, value, () => Limit); }
      }

      private Nullable<float> _value;
      public Nullable<float> Value
      {
         get { return _value; }
         set { PropertyChanged.ChangeAndNotify(ref _value, value, () => Value); }
      }

      public event PropertyChangedEventHandler PropertyChanged;
   }
}
