//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineState
    {
        public long Pkey_State { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> State { get; set; }
    }
}
