//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
   using System;
   using System.Collections.Generic;
   using System.ComponentModel;

    public partial class PDI : INotifyPropertyChanged, IPDI {
        private long _pKEY_PDI;
        public long PKEY_PDI {
            get { return _pKEY_PDI; }
            set { PropertyChanged.ChangeAndNotify(ref _pKEY_PDI, value, () => PKEY_PDI); }
        }

        private string _plateID;
        public string PlateID {
            get { return _plateID; }
            set { PropertyChanged.ChangeAndNotify(ref _plateID, value, () => PlateID); }
        }

        private string _materialID;
        public string MaterialID {
            get { return _materialID; }
            set { PropertyChanged.ChangeAndNotify(ref _materialID, value, () => MaterialID); }
        }

        private string _steelGrade;
        public string SteelGrade {
            get { return _steelGrade; }
            set { PropertyChanged.ChangeAndNotify(ref _steelGrade, value, () => SteelGrade); }
        }

        private Nullable<System.DateTime> _date;
        public Nullable<System.DateTime> Date {
            get { return _date; }
            set { PropertyChanged.ChangeAndNotify(ref _date, value, () => Date); }
        }

        private Nullable<float> _length;
        public Nullable<float> Length {
            get { return _length; }
            set { PropertyChanged.ChangeAndNotify(ref _length, value, () => Length); }
        }
        private Nullable<float> _width;
        public Nullable<float> Width {
            get { return _width; }
            set { PropertyChanged.ChangeAndNotify(ref _width, value, () => Width); }
        }
        private Nullable<float> _thickness;
        public Nullable<float> Thickness {
            get { return _thickness; }
            set { PropertyChanged.ChangeAndNotify(ref _thickness, value, () => Thickness); }
        }
        private Nullable<float> _yieldPoint;
        public Nullable<float> YieldPoint {
            get { return _yieldPoint; }
            set { PropertyChanged.ChangeAndNotify(ref _yieldPoint, value, () => YieldPoint); }
        }
        private Nullable<float> _tensileStrength;
        public Nullable<float> TensileStrength {
            get { return _tensileStrength; }
            set { PropertyChanged.ChangeAndNotify(ref _tensileStrength, value, () => TensileStrength); }
        }
        private Nullable<short> _measuringCode;
        public Nullable<short> MeasuringCode {
            get { return _measuringCode; }
            set { PropertyChanged.ChangeAndNotify(ref _measuringCode, value, () => MeasuringCode); }
        }
        private Nullable<float> _ruler1MCrossPDI;
        public Nullable<float> Ruler1MCrossPDI {
            get { return _ruler1MCrossPDI; }
            set { PropertyChanged.ChangeAndNotify(ref _ruler1MCrossPDI, value, () => Ruler1MCrossPDI); }
        }
        private Nullable<float> _ruler1MLengthPDI;
        public Nullable<float> Ruler1MLengthPDI {
            get { return _ruler1MLengthPDI; }
            set { PropertyChanged.ChangeAndNotify(ref _ruler1MLengthPDI, value, () => Ruler1MLengthPDI); }
        }
        private Nullable<float> _ruler2MLengthPDI;
        public Nullable<float> Ruler2MLengthPDI {
            get { return _ruler2MLengthPDI; }
            set { PropertyChanged.ChangeAndNotify(ref _ruler2MLengthPDI, value, () => Ruler2MLengthPDI); }
        }
        private Nullable<short> _leveling;
        public Nullable<short> Leveling {
            get { return _leveling; }
            set { PropertyChanged.ChangeAndNotify(ref _leveling, value, () => Leveling); }
        }
        private Nullable<float> _eModule;
        public Nullable<float> EModule {
            get { return _eModule; }
            set { PropertyChanged.ChangeAndNotify(ref _eModule, value, () => EModule); }
        }
        private Nullable<float> _gapLengthBow;
        public Nullable<float> GapLengthBow {
            get { return _gapLengthBow; }
            set { PropertyChanged.ChangeAndNotify(ref _gapLengthBow, value, () => GapLengthBow); }
        }
        private Nullable<float> _gapCrossBow;
        public Nullable<float> GapCrossBow {
            get { return _gapCrossBow; }
            set { PropertyChanged.ChangeAndNotify(ref _gapCrossBow, value, () => GapCrossBow); }
        }
        private Nullable<short> _manual;
        public Nullable<short> Manual {
            get { return _manual; }
            set { PropertyChanged.ChangeAndNotify(ref _manual, value, () => Manual); }
        }
        private Nullable<short> _location;
        public Nullable<short> Location {
            get { return _location; }
            set { PropertyChanged.ChangeAndNotify(ref _location, value, () => Location); }
        }
        private Nullable<int> _state;
        public Nullable<int> State {
            get { return _state; }
            set { PropertyChanged.ChangeAndNotify(ref _state, value, () => State); }
        }

        private LocationDef _locationState;
        public LocationDef LocationState {
            get { return _location.HasValue ? (LocationDef)_location.Value : LocationDef.New_Plate; }
        }
        public event PropertyChangedEventHandler PropertyChanged;
    }
}
