//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
    using System;
    using System.Collections.Generic;

    public partial class PreSettingsOutlet : IPreSettingsOutlet {
        public long Pkey_SettingsOutlet { get; set; }
        public Nullable<float> StartRangeThickness { get; set; }
        public Nullable<float> EndRangeThickness { get; set; }
        public Nullable<float> StartRangeActYieldPoint { get; set; }
        public Nullable<float> EndRangeActYieldPoint { get; set; }
        public Nullable<float> Offset { get; set; }
    }
}
