//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
    using System;
    using System.Collections.Generic;

    public partial class PreSetting : IPreSetting {
        public long PKEY_SETTINGS { get; set; }
        public string MaterialID { get; set; }
        public Nullable<int> CassetteNo { get; set; }
        public int Enable { get; set; }
        public Nullable<float> StartRangeThickness { get; set; }
        public Nullable<float> EndRangeThickness { get; set; }
        public Nullable<float> StartRangeWidth { get; set; }
        public Nullable<float> EndRangeWidth { get; set; }
        public Nullable<float> CorrPlastification { get; set; }
        public Nullable<float> CenterHeightBending { get; set; }
        public Nullable<float> CurveProfile { get; set; }
        public Nullable<float> TiltingLeft { get; set; }
        public Nullable<float> TiltingRight { get; set; }
    }
}
