//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
    using System;
    using System.Collections.Generic;

    public partial class ProductionReport : IProductionReport {
        public long PKEY_PROD { get; set; }
        public Nullable<System.DateTime> ProdDate { get; set; }
        public string PlateID { get; set; }
        public string MaterialID { get; set; }
        public Nullable<int> Leveling { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> NoOfLeveling { get; set; }
        public Nullable<int> CassetteNo { get; set; }
        public Nullable<float> SetLevelerInlet { get; set; }
        public Nullable<float> SetLevelerOutlet { get; set; }
        public Nullable<float> SetTiltLeft { get; set; }
        public Nullable<float> SetTiltRight { get; set; }
        public Nullable<float> SetMiddleHeight { get; set; }
        public Nullable<float> SetCurveProfile { get; set; }
        public Nullable<float> ActLevelerInlet { get; set; }
        public Nullable<float> ActLevelerOutlet { get; set; }
        public Nullable<float> ActTiltLeft { get; set; }
        public Nullable<float> ActTiltRight { get; set; }
        public Nullable<float> ActMiddleHeight { get; set; }
        public Nullable<float> ActCurveProfile { get; set; }
        public Nullable<float> ActEdgeWaveLeft { get; set; }
        public Nullable<int> ActNoEdgeWaveLeft { get; set; }
        public Nullable<float> ActEdgeWaveRight { get; set; }
        public Nullable<int> ActNoEdgeWaveRight { get; set; }
        public Nullable<float> ActCenterWave { get; set; }
        public Nullable<int> ActNoCenterWave { get; set; }
        public Nullable<float> SkiHead { get; set; }
        public Nullable<float> SkiTail { get; set; }
        public Nullable<float> TensileStrength { get; set; }
        public Nullable<int> MeasuringCode { get; set; }
        public Nullable<float> Set1MRulerCross { get; set; }
        public Nullable<float> Act1MRulerCross { get; set; }
        public Nullable<float> Set1MRulerLength { get; set; }
        public Nullable<float> Act1MRulerLength { get; set; }
        public Nullable<float> Set2MRulerLength { get; set; }
        public Nullable<float> Act2MRulerLength { get; set; }
        public Nullable<float> GapLengthBow { get; set; }
        public Nullable<float> ActGapLengthBow { get; set; }
        public Nullable<float> GapCrossBow { get; set; }
        public Nullable<float> ActGapCrossBow { get; set; }
        public Nullable<float> Temperature { get; set; }
        public Nullable<float> ActTemperature { get; set; }

        public void SetPlateData(IPDI pdi) {
            PlateID = pdi.PlateID;
            MaterialID = pdi.MaterialID;
            GapCrossBow = pdi.GapCrossBow;
            GapLengthBow = pdi.GapLengthBow;
            Set1MRulerCross = pdi.Ruler1MCrossPDI;
            Set1MRulerLength = pdi.Ruler1MLengthPDI;
            Set2MRulerLength = pdi.Ruler2MLengthPDI;
            TensileStrength = pdi.TensileStrength;
        }

        public void SetLevelerData(ILevelerData data) {
            ActCurveProfile = data.CurveProfile;
            ActLevelerInlet = data.LevelerInlet;
            ActLevelerOutlet = data.LevelerOutlet;
            ActMiddleHeight = data.MiddleHeight;
            ActTiltLeft = data.TiltLeft;
            ActTiltRight = data.TiltRight;
            ActTemperature = data.Temperature;
            //NoOfLeveling = data.NoOfLeveling;
            Leveling = data.Leveling;
            State = data.State;
        }

        public void SetFlatnessData(IFlatness flat) {
            Act1MRulerCross = (float)flat.ActRuler1MCross / 100f;
            Act1MRulerLength = (float)flat.ActRuler1MLength / 100f;
            Act2MRulerLength = (float)flat.ActRuler2MLength / 100f;
            ActGapCrossBow = (float)flat.GapCrossBow / 100f;
            ActGapLengthBow = (float)flat.GapLengthBow / 100f;
            SkiHead = (float)flat.SkiHead / 100f;
            SkiTail = (float)flat.SkiTail / 100f;
            ActEdgeWaveLeft = (float)flat.HeightWaveLeft / 100f;
            ActNoEdgeWaveLeft = flat.NumberWaveLeft;
            ActEdgeWaveRight = (float)flat.HeightWaveRight / 100f;
            ActNoEdgeWaveRight = flat.NumberWaveRight;
            ActCenterWave = (float)flat.HeightWaveCenter;
            ActNoCenterWave = flat.NumberWaveCenter;
            MeasuringCode = flat.MeasuringCode;
        }

        public void SetSettingsData(ISettingsData settings) {
            SetLevelerInlet = settings.LevelerInlet;
            SetLevelerOutlet = settings.LevelerOutlet;
            SetTiltLeft = settings.TiltLeft;
            SetTiltRight = settings.TiltRight;
            SetCurveProfile = settings.CurveProfile;
            SetMiddleHeight = settings.MiddleHeight;
        }
    }
}
