//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        public int ID { get; set; }
        public string ProduktName { get; set; }
        public Nullable<int> Discontinued { get; set; }
    }
}
