//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level2.PlateLeveler.DataTypes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp
    {
        public int PKEY_TEMP { get; set; }
        public string Steelgrade { get; set; }
        public Nullable<float> Temperature { get; set; }
        public Nullable<float> YieldPoint { get; set; }
        public Nullable<float> EModule { get; set; }
    }
}
